L=../lib
U=../utils

CFLAGS=-Wall -pedantic -std=c11 -I${U} -L${L} -g
LIBS=-lutils -lcurl

pgloadtest2:
						gcc $(CFLAGS) pgloadtest2.c $(LIBS) -o $@
crawler_step5_pgload:
						gcc $(CFLAGS) crawler_step5_pgload.c $(LIBS) -o $@
