L=../lib
U=../utils

CFLAGS=-Wall -pedantic -std=c11 -I${U} -L${L} -g
LIBS=-lutils -lcurl

crawler:
				gcc $(CFLAGS) crawler.c $(LIBS) -o $@

crawler2:
				gcc $(CFLAGS) crawler2.c $(LIBS) -o $@

crawler3:
				gcc $(CFLAGS) crawler3.c $(LIBS) -o $@
